# Generated by Django 5.1.6 on 2025-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebase',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
