# Generated by Django 5.1.6 on 2025-04-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebase',
            name='link',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
